import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
// import AuthProvider from "../contexts/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <AuthProvider> */}
        <Navbar />
        <div className="mx-auto min-h-dvh w-full px-4 py-24 md:max-w-[1208px]">
          {children}
        </div>
        <Footer />
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
